name: Simple CI

on:
  push:
    branches:
      - main  # Pokreće se na svaki push na 'main' granu

jobs:
  test:
    runs-on: ubuntu-latest  # Koristi Ubuntu za izvršavanje

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Preuzima kod

      - name: Run tests
        run: echo "Running tests..."  # Ovaj deo možeš zameniti sa stvarnim testovima, ako i



