name: Simple CI

on:
  push:
    branches:
      - main  # Pokreće se na svaki push na 'main' granu

jobs:
  test:
    runs-on: ubuntu-latest  # Koristi Ubuntu za izvršavanje

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Preuzima kod

      - name: Run tests
        run: echo "Running tests..."  # Ovaj deo možeš zameniti sa stvarnim testovima, ako i

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependecies
        run: |
          python -p pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

